clean:
module: "TunnelKit"
author: "Davide De Rosa"
author_url: "https://github.com/passepartoutvpn/tunnelkit"

theme: fullwidth

xcodebuild_arguments:
    - "-workspace"
    - "TunnelKit.xcworkspace"
    - "-scheme"
    - "TunnelKit-iOS"

custom_categories:
    - name: Core
      children:
        - BidirectionalState
        - ConfigurationError
        - EndpointProtocol
        - IOInterface
        - IPv4Settings
        - IPv6Settings
        - LinkInterface
        - Proxy
        - Session
        - SocketType
        - TunnelInterface
    - name: OpenVPN
      children:
        - OpenVPN
        - OpenVPNError
        - OpenVPNSession
        - OpenVPNSessionDelegate
    - name: AppExtension
      children:
        - OpenVPNTunnelProvider
