clean:
module: "TunnelKit"
author: "Davide De Rosa"
author_url: "https://github.com/keeshux/TunnelKit"

theme: fullwidth

xcodebuild_arguments:
    - "-workspace"
    - "TunnelKit.xcworkspace"
    - "-scheme"
    - "TunnelKit-iOS"

custom_categories:
    - name: Core
      children:
        - EncryptionProxy
        - IOInterface
        - LinkInterface
        - TunnelInterface
        - SessionProxy
        - SessionProxyDelegate
        - SessionError
    - name: AppExtension
      children:
        - Certificate
        - TunnelKitProvider
