clean:
module: "TunnelKit"
author: "Davide De Rosa"
author_url: "https://github.com/keeshux/TunnelKit"

theme: fullwidth

xcodebuild_arguments:
    - "-workspace"
    - "TunnelKit.xcworkspace"
    - "-scheme"
    - "TunnelKit-iOS"

custom_categories:
    - name: Core
      children:
        - IOInterface
        - LinkInterface
        - TunnelInterface
        - BidirectionalState
        - StaticKey
        - SessionProxy
        - SessionProxyDelegate
        - ConfigurationError
        - SessionReply
        - IPv4Settings
        - IPv6Settings
        - SessionError
        - SocketType
        - EndpointProtocol
        - ConfigurationParser
    - name: AppExtension
      children:
        - CryptoContainer
        - TunnelKitProvider
